apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: provider
spec:
  hosts:
    - provider
    - provider.gitops-nxm-v2.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: "/req"
      route:
        - destination:
            host: provider.gitops-ns1.svc.cluster.local
            port:
              number: 80
