apiVersion: v1
kind: Pod
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.6.0
      command: ["sleep", "600"]
      resources:
        limits:
          memory: "32Mi"
          cpu: "250m"
